[package]
name = "not-perl"
version = "0.1.0"
authors = ["Alek Ratzloff <alekratz@gmail.com>"]

[dependencies]
matches = "*"
lazy_static = "1"
enum-methods = "0.0.8"
#galvanic-test = "0.1"
failure = "0.1"
failure_derive = "0.1"
